### ISSUE TITLE
Groups MVP

### ISSUE THREAD

**Issue by S4mmyb** [regen-network/groups-ui#29]
**Acceptance Criteria**
- [x] Anyone can create a group with the group UI
- [x]  Every group (whether created through UI or CLI) ca be viewed by a member (as a group that I'm a member of)
- [x]  If user is admin, they can manage group & group policies
- [x]  Text, Staking, Send, Group admin msgs, proposals can be made through the UI
- [x]  Every proposal type (made via UI or CLI) can be viewed, voted on, & executed

******Nice to have / v2******

- [ ]  Text proposals can render as markdown in the UI
- [x]  Members can be managed through the UI (both for group policy as admin, as well as single admin)

**Comment by ryanchristo** [comment]
Closing this out after moving https://github.com/regen-network/indexer/issues/22 (already completed) and #121 to #151 where we can track a followup set of fixes and improvements as part of a next release.
